### ISSUE TITLE
Rename nix-tools

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/nix-tools#45] opened 2019-04-02 13:26 UTC
`nix-tools` sounds like it could be any set of generic tools for working with nix. It should at least have some reference to Haskell in the name.

This will be annoying, but only more annoying as time goes on. I've already seen some people be confused by it.

Name suggestion: `haskell-builds-to-nix`

**Comment by angerman** [comment] 2019-04-02 13:37
Dupe of input-output-hk/haskell.nix#94

**Closed by angerman** 2019-04-02 13:37 UTC
